baseURL = 'https://wnagdouble.github.io/'
languageCode = 'zh-CN'
theme = "JuiceBar"
title = "Double Blog"

[params]
author = "Wang Double"
description = "人生如逆旅，我亦是行人。"
authorImage = "/images/profile.jpg"
paginate = 5 
Title = "Wang Double"
content = "爱卿，你可知罪   (ˊ˘ˋ*)♡"
imageUrl = "/images/avatar.jpg"

# To add a new social icon 
# More social icons can be found in JuiceBar\layouts\partials\svg.html.
[[params.social]]
name = "email"
url = "mailto:muadouble@gmail.com"

[taxonomies]
category = "categories"
tag = "tags"

# To add a new navigation link
[[menu.main]]
name = "Todo"
url = "/todo"
[[menu.main]]
name = "Blog"
url = "/post"
[[menu.main]]
name = "Categories"
url = "/categories"
[[menu.main]]
name = "About"
url = "/about"

# If using the giscus commenting system
[params.giscus]
repo = "wnagDouble/wnagdouble.github.io"
repoID = "R_kgDOKL5y6g"
category = "Announcements"
categoryID = "DIC_kwDOKL5y6s4Cb9eJ"
mapping = "og:title"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
lang = "zh-CN"
loading = "lazy"

# Used for outputting the documentation (required).
[outputs]
home = ["HTML", "RSS", "JSON"]